version: 2

project_name: kairos-init
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s -X "github.com/kairos-io/kairos-init/pkg/values.VERSION={{.Tag}}"
    binary: '{{ .ProjectName }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"