version: 2

project_name: kairos-init
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      - ARCH={{ .Arch }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      pre:
        - make
    ldflags:
      - -w -s -X "github.com/kairos-io/kairos-init/pkg/values.version={{.Tag}}" -X "github.com/kairos-io/kairos-init/pkg/values.gitCommit={{.ShortCommit}}"
    binary: '{{ .ProjectName }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"