name: Docker image build

on:
  push:
    branches:
      - 'main'

concurrency:
  group: build-main-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  dockerImage:
    env:
      REGISTRY: "ttl.sh"
    runs-on: "ubuntu-24.04"
    name: Docker image
    steps:
      - uses: actions/checkout@v4
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ttl.sh/kairos-init
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: "linux/amd64", "linux/arm64"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}