name: docker build images

on:
  pull_request:
  push:
    branches:
      - 'main'

concurrency:
  group: build-image-matrix-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  testing_build_matrix:
    name: ${{ matrix.base_image }} - ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ "linux/amd64" ]
        base_image: [ "ubuntu:24.04", "debian:12", "alpine:3.19", "opensuse/leap:15.6", "rockylinux:9" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          tags: kairos-${{ matrix.base_image }}
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}